# Site settings
title: Raghav Ramesh
description: 'Cloud Engineer at JP Morgan Chase & Co.'
url: 'http://raghavramesh.github.io'
baseurl: '/'
google_analytics: 'UA-56675128-1'
disqus_shortname: 'raghavs-blog'

author:
  name: 'Raghav Ramesh'
  email: raghavramesh94@gmail.com
  twitter_username: raghavramesh94
  # facebook_username: raghav213
  github_username:  RaghavRamesh
  linkedin_username:  raghavramesh21

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
